---
#Nginx role tasks

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Create Nginx directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/nginx/conf.d
    - "{{ nginx_root }}"

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx

- name: Configure virtual host
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx

- name: Create sample webpage
  copy:
    content: "{{ website_content }}"
    dest: "{{ nginx_root }}/index.html"
    owner: root
    group: root
    mode: 0644

- name: Configure SELinux for Nginx
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: Configure firewall for Nginx
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  when: firewall_enabled | default(true) | bool

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes